# Generated by Django 4.2.4 on 2023-08-27 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='download_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
